---
title: "Character distribution"
author: "Thibault Clérice & JB Camps"
date: "10/23/2019 - 2/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("ggplot2")
```


# Dispersion + Regression

```{r}
d = read.csv("chars_classes/datasets-characters.csv", header = TRUE)
d = d[d[,1] != "Full",]

qplot(size, classes, colour=dataset, data = d) + geom_smooth(method='lm', formula= y~x)

# Global reg
reg = lm(formula = classes ~ size, data = d)
summary(reg)

# reg students
reg = lm(formula = classes ~ size, data = d[d[, "dataset"] == "students", ])
summary(reg)

# reg pinche
reg = lm(formula = classes ~ size, data = d[d[, "dataset"] == "pinche", ])
summary(reg)
```


# Violin plot version

## OCR Training set

### Load data

```{r}
data = read.csv("pipeline/chars.csv", header = TRUE, row.names = 1)
# c'en est déjà un
#df =  as.data.frame(data)
data = cbind(data, "Pinche")
colnames(data)[2] = "Corpus"
```

## Students

```{r}
data_students = read.csv("pipeline/chars_students.csv", header = TRUE, row.names = 1)
data_students = cbind(data_students, "TNAH")
colnames(data_students)[2] = "Corpus"
```

## Text lengths

```{r, fig.width=5, fig.height=5, out.width=500, out.height=500, dpi = 300}
#ggplot(c(df, df_students), aes(x="", y=occs)) + geom_violin() + geom_boxplot(width=0.2) + ylab("Characters with this count") + xlab("Est. count of characters in the TNAH Dataset") + scale_y_log10()
main = "Violin and boxplot of character frequencies"
ylab= "Frequency"
df = rbind(data, data_students)
ggplot(df, aes_(x = quote(Corpus), y = quote(occs))) +
      ggtitle(main) +
      ylab(ylab) +
#      xlab(xlab) +
      geom_violin() + 
      geom_boxplot(width=0.1) +
      #theme(axis.text.x = element_text(size = rel(0.7))) +
  scale_y_log10()
```
